### ISSUE TITLE
About input bam files

### ISSUE THREAD

**Issue by oghzzang** [xunchen85/ERVcaller#10]
Dear ERVcaller team, 

Hi, I'm Oh.  

Thanks for your program. 

Then, I have a question. 

Can I use GATK pre-processed bam files for input bam of ERVcaller? 

I have only pre-processed bam files. In this text, pre-processing means sorting, marking duplicate reads, and recalibrating (https://gatk.broadinstitute.org/hc/en-us/articles/360035535912-Data-pre-processing-for-variant-discovery). 

Many Thanks. 

Oh.

**Comment by xunchen85** [comment]
Hi Oh,

You should be able to use any bam files if it follows the BAM format.

Best,
Xun

**Comment by oghzzang** [comment]
Thanks for your quick reply. 

Best, 

Oh
