### ISSUE TITLE
About "xx_h1_sorted.bam" file

### ISSUE THREAD

**Issue by oghzzang** [xunchen85/ERVcaller#12]
Dear ERVcaller team.

Hi I'm Oh. 

I have executed your program. 
And I get output file, and output directory. 

When I use your test bam, I have only one output file (TE_seq.vcf), and one temp directory.

However, when I use my sample bam, I get one more file. 

--> 2016000051.vcf (Expected), **2016000051_h1_sorted.bam (No expected)**

What is "_h1_sorted.bam" file?

**Comment by xunchen85** [comment]
Can you show the commands that you are using? 

"_h1_sorted.bam" should be the whole-genome alignment file if you are using the fastq reads as the input. After you successfully got the VCF file, you can consider to either delete or keep it for other usages.

Xun

**Comment by oghzzang** [comment]
Hi Xun. 

Thanks for quick reply. 

I didn't use fastq reads as the input. 

perl $ERVcaller/ERVcaller_v1.4.pl \
-i ${Sample_name} \
-f .bam \
-H $Human_genome \
-T ${ERVdatabase}/Human_TE_library.fa \
-I ${Input_bam_dir} \
-O ${Output_dir} \
-r 150 \
-t 16 \
-S 40 \
-BWA_MEM \
-G 2>> ${Output_dir}/${Sample_name}.$Tool.log

**Comment by xunchen85** [comment]
Hi,

I may answer this question in another comment. Firstly you can check if your input BAM file is from BAM MEM; Secondly you can check if you sucessfully get the VCF file (with called TE loci) or the job may fail; Thirdly you also can run a 1KGP low-coverage sample HG00100 as a technical control, which I just ran successfully in few days.

Best,
Xun

**Comment by oghzzang** [comment]
Thank you. 

I'll check and try. 

Best, 
Oh
