### ISSUE TITLE
Length of TSD

### ISSUE THREAD

**Issue by 1577377232** [xunchen85/ERVcaller#29]
Hi xun,

Why is the TSD so long? Are these sites false positives, or what can I do about them?

Best，
Dan

**Comment by xunchen85** [comment]
Hi Dan,

It depends on the situation. First of all the TSD and length is estimated based on the two up-/down-stream breakpoints detected. But the TSD for some LINE elements could be very long too.

I would suggest you check some loci first. 

Best,
Xun

**Comment by 1577377232** [comment]
I used IGV to check the breakpoints, and extracted the reads mapped within 150bp from TSD, assembled and compared them. 
Is there a way to assemble a more complete ERV, via discordant reads or split reads? Because I saw in the VCF file,INFO column,INFOR information is exciting！ very complete. For example, INFOR=ERV3, 1,7525,7525.

Best,
Dan
