### ISSUE TITLE
The Requirement software

### ISSUE THREAD

**Issue by zhutao1009** [xunchen85/ERVcaller#3]
Hi chenxu：
  Does Hydra-Version-0.5.3 is required by ERVcaller？It seem that 2.2 and 3.1 is conflicting in User Manual of ERVcaller v1.4.

**Comment by xunchen85** [comment]
It was updated, and the latest ERVcaller v1.4 do not use Hydra-Version-0.5.3. I will remove it from section 3.1 in the User Manual
