### ISSUE TITLE
The help message of ERVcaller_v1.4.pl

### ISSUE THREAD

**Issue by zhutao1009** [xunchen85/ERVcaller#4]
After I typed the command `$perl  ERVcaller_v1.4.pl`, I got the help message and examples, but I found the examples is conflicting with User Manual of ERVcaller v1.4 
The help message is as follows:
perl  ./ERVcaller_v1.4.pl

Examples for detecting ERV and other TE insertions:
# Detecting TE insertions with a BAM file as the input
       perl /vol6/home/quluj/zt/software/ERVcaller_v1.4/ERVcaller_v1.4.pl -i TE_seq.fa -f .bam -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM

# Detecting TE insertions with paired-end FASTQ file as the input
       perl /vol6/home/quluj/zt/software/ERVcaller_v1.4/ERVcaller_v1.4.pl -i TE_seq.fa -f .fq.gz -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM

# Detecting TE insertions with separated BAM file(s) as the input
       perl /vol6/home/quluj/zt/software/ERVcaller_v1.4/ERVcaller_v1.4.pl -i TE_seq.fa -f .list -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM -m

# Detecting and genotyping TE insertions with a BAM file as the input
       perl /vol6/home/quluj/zt/software/ERVcaller_v1.4/ERVcaller_v1.4.pl -i TE_seq.fa -f .bam -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM -G

**Comment by xunchen85** [comment]
Can you help to point out the inconsistency with the following ERVcaller_v1.4 user manual? Thanks!

$ perl user_installed_path/ERVcaller_v1.4.pl -i sample_ID -f .bam -H hg38.fa -T TE_consensus.fa –S 20 -BWA_MEM –t threads

3.3.1 Detecting TE insertions using a BAM file as input
_$ perl user_installed_path/ERVcaller_v.1.4.pl -i TE_seq -f .bam -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM_ 

3.3.2 Detecting TE insertions using paired-end FASTQ file as input
_$ perl user_installed_path/ERVcaller_v.1.4.pl -i TE_seq -f .fq.gz -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM_ 

3.3.3 Detecting TE insertions using multiple BAM files as input
_$ perl user_installed_path/ERVcaller_v.1.4.pl -i TE_seq -f .list -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM -m_ 

3.3.4 Detecting and genotyping TE insertions using a BAM file as input
_$ perl user_installed_path/ERVcaller_v.1.4.pl -i TE_seq -f .bam -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM -G_

**Comment by zhutao1009** [comment]
-i  TEseq, it should be -i Sample_name

**Comment by xunchen85** [comment]
Sorry for the confusion, the "TE_seq" is used as the name of the example input data with the ERVcaller_v1.4. 

I have corrected the "TE_seq.fa" in the ERVcaller_v1.4.pl main script.
