### ISSUE TITLE
Illegal division by zero

### ISSUE THREAD

**Issue by zhutao1009** [xunchen85/ERVcaller#5]
when @insert_size =0, the script will report errors.
Illegal division by zero at /vol6/home/quluj/zt/software/ERVcaller_v1.4/ERVcaller_v1.4.pl line 1623

**Comment by xunchen85** [comment]
It is not allow to have insert size = 0, i will further specify it in the updated manual. 

Meanwhile, the term of "insert size" we used here included the read length, thus it won't be 0 even you the two paired-end have overlapped sequences. For example, the 100 bp paired-end reads have 30 bp overlapped regions, the insert size should be 170 bp (100+100-30)

**Comment by zhutao1009** [comment]
Thanks! What option I should use? --l (length_insertsize) or -L (L_std_insertsize)

**Comment by xunchen85** [comment]
Ideally you should use both, -l is the mean value and -L is the std. You can calculate it using many other tools, such as GATK. 

If you don't use both of them, ERVcaller can calculate it using implemented tool. let me know if the implemented tool cannot accurately calculate it.

**Comment by zhutao1009** [comment]
I have a fasta file that contain 90 TE sequence，do you mean that I should calculating the average TE length and standard deviation of TE length before running ERcaller？

**Comment by xunchen85** [comment]
The insert size is a used for the NGS data not the 90 TE reference sequences in FASTA format.

**Comment by zhutao1009** [comment]
Sorry, I don't understand.   : )

**Comment by xunchen85** [comment]
you can check this page about insert size: http://software.broadinstitute.org/software/igv/interpreting_insert_size. You can find more with the key words such as "NGS insert size"

**Comment by zhutao1009** [comment]
Thanks!
