### ISSUE TITLE
Error in User Manual

### ISSUE THREAD

**Issue by zhutao1009** [xunchen85/ERVcaller#6]
The original text is as follows：
3.3.2 Detecting TE insertions using paired-end FASTQ file as input
$ perl user_installed_path/ERVcaller_v.1.4.pl -i TE_seq -f .fq.gz -H hg38.fa -T TE_consensus.fa -I folder_of_input_data -O folder_for_output_files -t 12 -S 20 -BWA_MEM
如果使用了-BWA_MEM 参数会导致程序把输入文件当成bam文件，需要去掉-BWA_MEM程序才能正常运行

**Comment by xunchen85** [comment]
it make sense, -BWA_MEM is a parameter for the use of BAM files as the input. The help page of ERVcaller_v1.4.pl script is corrected. I will corrected the corresponding sentence in the manual.
